docker/config/rabbitmq-definitions.json

Added new RabbitMQ queue to handle registry manager commands, such as "update-archive-status"
Check that "manager.commands" queue  was created in RabbitMQ.
https://github.com/NASA-PDS/pds-registry-app/issues/223
https://github.com/NASA-PDS/pds-registry-app/issues/224

New RabbitMQ queue

---

Jenkinsfile
docker/certs/generate-certs.sh

Merge this to resolve #120 which gets OpenSearch working in the CD environment. The crux of the issue was the following:
```console
$ ls -l certs
-rw-r--r--. 1 pds4 pds 1704 Oct 12 13:09 node1-key.pem
-rw-------. 1 pds4 pds 1204 Oct 12 13:09 node1.pem
-rw-------. 1 pds4 pds 1679 Oct 12 13:09 root-ca-key.pem
-rw-------. 1 pds4 pds 1326 Oct 12 13:09 root-ca.pem
-rw-r--r--. 1 pds4 pds   41 Oct 12 13:09 root-ca.srl
```
```console
$ ls -l certs
-rw-r--r--. 1 root staff 1704 Oct 12 13:09 node1-key.pem
-rw-------. 1 root staff 1204 Oct 12 13:09 node1.pem
-rw-------. 1 root staff 1679 Oct 12 13:09 root-ca-key.pem
-rw-------. 1 root staff 1326 Oct 12 13:09 root-ca.pem
-rw-r--r--. 1 root staff   41 Oct 12 13:09 root-ca.srl
```
When OpenSearch tried to open the files `node1.pem` it was read-only to …

Resolve #120

---

docker/.env
docker/default-config/application.properties
docker/docker-compose.yml

…right with it yet
We want to reproduce the behavior in production where the api is behind a path /api/search/1/...
To simplify, I expose the api on the proxycrypt on port 443 (default as in production), since it otherwise leads us to more complication on the registry-api side.
To test, one need to call:
https://localhost/api/search/1/
Which does not work right now because more work is required on registry-api side.

add proxy to the path and use latest docker images

---

Jenkinsfile
docker/.env
docker/certs/generate-certs.sh

This upgrades OpenSearch to 1.2.4, adds some safety cleanup to `generate-certs.sh`, and updates the Jenkins pipeline to include certificate generation.
However, when I run `int-tests.sh`, every single test fails and I don't know why. Could @ramesh-maddegoda @tloubrieu-jpl take a look?
Pending.
- #146

Update OpenSearch to fix issue with deploying on Linux #146

---

Jenkinsfile
docker/docker-compose.yml
docker/int-test.sh

Support end-to-end integration tests on Jenkins:
- by including `reg-api-integration-test` in the `Jenkinsfile` 
- by removing all profiles from `reg-api-integration-test-with-wait` because any results of those tests are lost in the `up --detach`
Although the `Jenkinsfile` doesn't use the `int-test.sh` script, as a bonus of merging this, you'll help prevent the proliferation of stray containers in that script.
See [this failed run](https://pds-jenkins.jpl.nasa.gov/job/Registry/332/), which _is expected_, because `reg-api-integration-test` currently does indeed fail.
- https://github.com/NASA-PDS/deep-archive/issues/138 (this is 1 of 2 pull requests)

Support end-to-end integration tests on Jenkins

---

docker/default-config/application.properties
docker/docker-compose.yml
docker/postman/postman_collection.json

Changes to test registry-api behind a reverve proxy
Tests for PR https://github.com/NASA-PDS/registry-api/pull/254

Add tests for verifying Swagger UI per NASA-PDS/registry-api#254

---

Jenkinsfile
docker/int-test-for-jenkins.sh
fail.sh

Merge this and you'll get to actually see the output of `docker compose run reg-api-integration-test` whenever Jenkins does its daily deploy and test of the Registry.
See an actual such log at: https://pds-jenkins.jpl.nasa.gov/job/Registry/364/execution/node/49/log/
- [devops#33](https://github.com/NASA-PDS/devops/issues/33)

Produce full integration test logs in Jenkins

---

docs/source/user/load1.rst

The auth.cfg ile content description was not easy to find, I added a cross reference from the quickstart to the reference description of the file.
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests
Fixes #170

Add cross reference for auth.cfg description in the documentation

---

.pre-commit-config.yaml
docker/.env
docker/default-config/application.properties
docker/docker-compose.yml
docker/postman/postman_collection.json
src/pds/registry/__init__.py

- Update version number of registry-api.
- Update test suite
- Add provenance script to docker compose
Run the integration tests with:
docker compose --profile=int-registry-batch-loader up
Fixes https://github.com/NASA-PDS/registry/issues/140

update for v1.2.0, add provenance script in docker compose

---

docker/postman/postman_collection.json

Adds tests for the following PRs
https://github.com/NASA-PDS/registry-api/pull/322
https://github.com/NASA-PDS/registry-api/pull/328
Postman tests pass
Github Branch tests fail due to (at least) lint, but that's nothing new and unrelated to this PR. 
https://github.com/NASA-PDS/registry-api/issues/277
https://github.com/NASA-PDS/registry-api/issues/326
Do not de-draft/merge until relevant registry-api PRs are merged (@jordanpadams @tloubrieu-jpl related: https://jpl.slack.com/archives/GCGR1R3A4/p1682534613061049)

Registry api tests 277 326

---

docker/.env
docker/docker-compose.yml

fixes https://github.com/NASA-PDS/registry/issues/198

Use new reference dataset for integration tests

---

Jenkinsfile
docker/docker-compose.yml
docker/int-test-for-jenkins.sh
docker/postman/postman_collection.json

Merge this to resolve [devops#35](https://github.com/NASA-PDS/devops/issues/35) which'll do the following:
-   Update the Jenkins pipeline so that TestRail credentials are available
-   Instantiate a service in the Docker Composition that runs Newman tests with the TestRail Reporter, using the credentials from above
-   In addition, it uses TestRail project ID 168 (which is PDS)
-   And TestRail suite ID 12824 (which is "PDS Registry API, automated tests")
- Adds the test case ID `C1274687` to a single test (with three assertions) in the Postman collection (which is "As an API user, I want to search by a temporal range as an ISO-8601 time interval")
- Jenkins: https://pds-jenkins.jpl.nasa.gov/job/Registry/454/
- TestRail: https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/3367 …

Automatically registers nightly test runs in CAE TestRail

---

docker/postman/postman_collection.json

registry-api PR 380 changes kvp format for array-like values
No tests to perform
related to https://github.com/NASA-PDS/registry-api/pull/380

update tests for registry-api PR 380

---

docker/docker-compose.yml
docker/postman/postman_collection.json

- Add legacy synchronization option to sweeper to test this case in the deployment
- Fix a minor failure in the postman tests

Add legacy sync to sweeper, fix integration test

---

docker/docker-compose.yml
docker/postman/postman_collection.json

Updates so that the latest postman test collection works with test automation, currently through jenkins with testrail export.
Once merged the latest test "[Registry API Newman tests via Jenkins" run should be successful on https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/overview/168

Opensearch postman

---

docker/docker-compose.yml

Since the integration test directly testing the opensearch content, options were missing for the newman run in one case. The options have been added .
That should make the integration test run successfully on a feature branch, with the github action.

fix integration test launcher

---

docker/postman/postman_collection.json

Implement tests
Adds default docker credentials for ease of development
Adds new tests and trivially-modifies a couple of others. All relevant tests pass
fixes https://github.com/NASA-PDS/registry-api/issues/484
fixes https://github.com/NASA-PDS/registry-api/issues/485
fixes https://github.com/NASA-PDS/registry-api/issues/486
fixes https://github.com/NASA-PDS/registry-api/issues/487

484 485 486 487 Membership latest tests

---

.pre-commit-config.yaml
docker/postman/postman_collection.json

adds tests for `/classes` API route prefix
tests for https://github.com/NASA-PDS/registry-api/pull/512

add tests for https://github.com/NASA-PDS/registry-api/pull/512

---

docker/postman/postman_collection.json

'nuf said
only new tests tested
related to https://github.com/NASA-PDS/registry-api/issues/495
related to https://github.com/NASA-PDS/registry-api/pull/524

implement tests for registry-api #524

---

docker/postman/postman_collection.json

The new tests aim at validating the upgrade made in PR https://github.com/NASA-PDS/registry-api/pull/526
Tests for PR https://github.com/NASA-PDS/registry-api/pull/526

add new tests for Q param on all end-points

---

README.md
src/pds/registry/utils/geostac/create_lola_pds4.py
src/pds/registry/utils/geostac/templates/product-browse-template.xml
src/pds/registry/utils/geostac/templates/product-external-template.xml
src/pds/registry/utils/treks/create_treks_pds4.py
src/pds/registry/utils/treks/product_service_builder.py
src/pds/registry/utils/treks/templates/product-collection-template.xml
src/pds/registry/utils/treks/templates/product-service-template.xml

Added references to GDR LOLA data into the GeoSTAC script. The data is considered derived from if their bounding boxes overlap. Also, per Sean's worry of invalid characters, it's also been fixed by adding a pipe to  encode characters such as & and <, >.
The labels are able to build and load into the registry.
Resolves #316

Add LID Reference to LOLA GDR in GeoSTAC script

---

docker/.env
src/pds/registry/utils/geostac/create_lola_pds4.py
src/pds/registry/utils/geostac/templates/product-browse-template.xml

Fix to make GIS scripts work in production environment

---

src/pds/registry/utils/geostac/create_lola_pds4.py

Fixes [https://github.com/NASA-PDS/registry/security/code-scanning/24](https://github.com/NASA-PDS/registry/security/code-scanning/24)
To fix the problem, we need to ensure that the Jinja2 `Environment` object is created with `autoescape` enabled. This can be done by using the `select_autoescape` function, which will automatically enable autoescaping for specific file extensions like HTML and XML. This change will prevent XSS attacks by escaping any untrusted input rendered in the templates.
We need to modify the creation of the `Environment` object in the `create_product_external` and `create_product_browse` functions to include `autoescape=select_autoescape(['html', 'xml'])`.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 24: Jinja2 templating with autoescape=False

---

docker/postman/postman_collection.json
setup.cfg

Implements a test that the number of total hits for _search is exactly equal to the expected number.
Assumes that the current count of 38 is correct - @jordanpadams is that a valid assumption?
Test passes (Postman, dockerized registry)
https://github.com/NASA-PDS/registry-api/issues/630#issuecomment-2779638308

implement test for NASA-PDS/registry-api#630

---

docker/.env
docker/docker-compose.yml
docker/postman/postman_collection.json
docker/scripts/elasticsearch-init.sh
setup.cfg

A review of the tests have been done and test unattended since the multitenant has been done have been re-integrated in the suite. 
the sweeper with legacy  registry has also been re-enabled by having the "registry" index alias created automatically in the docker compose setup (interim solution unitil registry-mgr does it).
Tested with docker compose setup, see:
```
docker-reg-api-integration-test-with-wait-1  | 
docker-reg-api-integration-test-with-wait-1  | ┌─────────────────────────┬───────────────────┬──────────────────┐
docker-reg-api-integration-test-with-wait-1  | │                         │          executed │           failed │
docker-reg-api-integration-test-with-wait-1  | ├─────────────────────────┼───────────────────┼──────────────────┤ …
```

Fix automated tests wth somewhat latest version of the components
