- .github/workflows/stable-cicd.yaml
- .github/workflows/unstable-cicd.yaml
> Updates per devops#19

- docker/README.md
Update the README file with a section to clean up the deployment
Refer to the task NASA-PDS/pds-registry-app#216
> Update the README file with a section to clean up the deployment

- docker/.env
- docker/README.md
- docker/docker-compose.yml
- docker/int-test.sh
- docker/pds-batch-loader.sh
- docker/pds-service-loader.sh
- docker/scripts/registry-api-waits-for-elasticsearch.sh
- docker/scripts/registry-loader-waits-for-elasticsearch.sh
Simple wrappers to call the pds-batch-loader, pds-service-loader and int-test docker compose services and additional code improvements
Refer to the task NASA-PDS/pds-registry-app#257
> Simple wrappers to call the pds-batch-loader, pds-service-loader and int-test docker compose services

- docker/.env
- docker/README.md
- docker/docker-compose.yml
Add changes to set the archive status of the test data
Refer to the task NASA-PDS/registry#31
> Add changes to set the archive status of the test data

- .gitignore
- Jenkinsfile
- docker/.env
- docker/README.md
- docker/docker-compose.yml
Merge this if you dare to make progress on [pds-api#51](https://github.com/NASA-PDS/pds-api/issues/51) and [devops#11](https://github.com/NASA-PDS/devops/issues/11) with the dream of having a Registry API with all the fixin's running on `pds-expo.jpl.nasa.gov`—including `https`.
[See here](https://pds-jenkins.jpl.nasa.gov/job/Registry/33/).
- [pds-api#51](https://github.com/NASA-PDS/pds-api/issues/51)
- [devops#11](https://github.com/NASA-PDS/devops/issues/11)
> Add Jenkins pipeline and ProxyCrypt

- docs/source/install/tools.rst
and make environment config optional
> Use latest release

- .github/workflows/branch-cicd.yaml
- docs/source/admin/ldd.rst
Created new entry under Admin -> Data Dictionaries which describes the registry-manager upgrade-dd command.
\## ♻️ Related Issues
[registry-loader #14](https://github.com/NASA-PDS/registry-loader/issues/14) - Add README / documentation for executing archive status update script and upgrade dd command
> Registry loader 14 - add documentation for upgrade-dd

- docs/source/user/delete_data.rst
- docs/source/user/harvest_job_configuration.rst
- docs/source/user/load1.rst
- docs/source/user/update_status.rst
Add notes on default opensearch port management in harvest parameters.
This is related to a feedback from Dan Scholes.
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests
> Opensearch port

- docker/.env
Updated the docker image versions to be released with Registry docker compose
> UPDATE The docker image versions to be released with Registry docker compose

- docker/.env
- docker/default-config/application.properties
- docker/postman/postman_collection.json
Brief summary of changes if not sufficiently described by commit messages.
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests
- fixes NASA-PDS/pds-api#234
- fixes https://github.com/NASA-PDS/pds-api/issues/196 
I did not find where to get the version of the application from, the only place where it is is in the maven project pom.xml, I believe we are loosing that when we launch the application inside docker with the java command.
> make nasa swagger skin work here

- docker/.env
- docker/default-config/application.properties
- docker/docker-compose.yml
- docker/postman/postman_collection.json
- docker/scripts/registry-api-waits-for-elasticsearch.sh
This Pull request adapts the docker compose deployment to work with a registry-api docker image generated with spring-boot (mvn spring-boot:build-image).
That should still work with docker images generated from the github actions CICD
> Spring boot docker

- docker/docker-compose.yml
Merge this to move the service endpoint back to port 8443.
Nope.
- #150
> Resolve #150

- docs/source/user/dashboards.rst
- docs/source/user/tasks.rst
Add a page to document the registry dashbaords.
Fixes #100
> Document available OpenSearch Dashboards per #100

- docs/source/user/load1.rst
- docs/source/user/load2.rst
> Add link to update status

- docker/default-config/application.properties
- docker/docker-compose.yml
Change the proxycrypt configuration to prperly set the port of the reverse proxy. To be used to test PR https://github.com/NASA-PDS/registry-api/pull/244
> set the port of the reverse proxy properly

- .github/workflows/secrets-detection.yaml
- .gitignore
- .pre-commit-config.yaml
- .secrets.baseline
Adds secrets detection.
Once merged, please update the branch protection rule for `main` to include secrets detection as one of the status checks.
N/A
- [software-issues-repo#55](https://github.com/NASA-PDS/software-issues-repo/issues/55)
> Add secrets detection

- docs/source/user/update_status.rst
Add a sentence to make clear which status set the product to be publicly available in the API.
Fixes https://github.com/NASA-PDS/registry-mgr/issues/71
> add documentation on the archive status.

- .secrets.baseline
Merge this to fix the secrets detection workflow as a result of changes for titan treks utility script.
See the [successful run in the sandbox](https://github.com/nasa-pds-engineering-node/registry/actions/runs/9812610823)
- #292
> Fixes secrets baseline for titan treks utility script

- docker/postman/postman_collection.json
implements tests for #223, #451, #452, #453, #454
test C-number UUIDs outstanding
> add tests for registry-api requirements 223, 451, 452, 453, 454

- docker/.env
- docker/default-config/opensearch.yml
- docker/postman/postman_collection.json
Test all the upgraded components (loader, sweeper, api) and update the tests in postman with more non regression tests.
> Required upgrades for multitenant Registry

- docker/postman/postman_collection.json
Part of the fixes to one test weren't included in export/PR.
Default API hostname was erroneously changed
> Hotfix to #299

- docker/postman/postman_collection.json
new tests 
Fixes https://github.com/NASA-PDS/registry-api/issues/497
> Blob removed tests

- docker/postman/postman_collection.json
Remove a couple of tests which were there as draft, uncompleted tests.
> remove draft/useless tests

- docker/postman/postman_collection.json
Add a test for requirement NASA-PDS/registry-api#439
> Add test for an API request from a web browser

- docker/postman/postman_collection.json
Add security tests.
to test ticket https://github.com/NASA-PDS/registry-api/issues/607
> Add security tests

- docker/postman/postman_collection.json
New tests for the Accept format accepted values.
For PR 
Refs https://github.com/NASA-PDS/registry-api/issues/440
Refs https://github.com/NASA-PDS/registry-api/issues/450
> add new accept format values for xml, pds4 xml and pds4 json

- docker/.env
- docker/default-config/application.properties
- docker/default-config/opensearch.yml
- docker/docker-compose.yml
- docker/postman/postman_collection.json
- setup.cfg
Update to make test work better.
However skipped tests are not supported by NewMan. This need to be reviewed further.
> Update and fix all broken tests (excluding expected skipped tests)

- docker/postman/postman_collection.json
Number of properties indexed is higher due to new LDD JSON being available.
> Test fix, after Insight LDD JSON has been published in expected version

- .github/workflows/branch-cicd.yaml
- .gitignore
- diagrams/README.md
- docs/source/conf.py
- docs/source/install/install.rst
- setup.cfg
- src/pds/registry/__init__.py
- tox.ini
* Update setup.cfg and tox for py313
* Upgrade dependencies
* Update version handling
* Upgrade branch CICD
```
sphinx-build -b html docs/source docs/build/html
```
refs https://github.com/NASA-PDS/template-repo-python/issues/105
> Upgrade to python 3.13
